name: ploc
main: de.hhhammer.ploc.Main
version: 1.0
author: hamburghammer
api-version: 1.16
commands:
  ploc:
    description: Get a location of an specific user.
    usage: /<command> <player>
    permission: ploc